[workspace]
resolver = "3"
members = ["wreck-live"]

[package]
name = "wreck"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.24.0", optional = true }
nalgebra = "*"

[features]
default = ["bytemuck"]
bytemuck = ["dep:bytemuck"]
